"""One-time recovery of ``breaks`` for attempts recorded before it was tracked.

``breaks`` (attempts.py / db.py) was added partway through this app's life, so
every attempt finished before that column existed has ``breaks = NULL`` even
though the value was fully determined at the time. It can be reconstructed
exactly, with no re-running of the search, because:

    matched_edges = checksBefore[fillOrder][bestDepth] - breaks

``checksBefore[depth]`` is how many of the board's internal edges the first
``depth`` placements have joined up under a given fill order -- a fixed
property of the order alone (see ScanSolver.java's own field of the same
name), not of the search, the seed, or the piece colours. The two arrays
below were generated once from the real `FillOrder.bandedScan(16)` /
`FillOrder.rowMajor(16)`, using the exact formula ScanSolver builds
`checksBefore` with; regenerate them (see the comment above each) if
`FillOrder.java`'s orders ever change.

An `MrvSolver` attempt (or one from before `engine` existed at all, i.e. the
single-solver app this project started as) never slips, so its breaks is
trivially 0 regardless of depth.

Run with:  python3 server/backfill_breaks.py [path/to/eternity2.sqlite]
Back up the database first -- this writes to it. Safe to re-run: it only ever
touches rows where breaks is still NULL.
"""

import json
import os
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_DB = os.path.join(ROOT, "data", "eternity2.sqlite")

# Generated by a one-off Java program that calls FillOrder.bandedScan(16) /
# FillOrder.rowMajor(16) and reproduces ScanSolver's checksBefore computation
# verbatim (northSlot/westSlot from the order, then one running sum). Index d
# is "internal edges joined up by the first d placements".
CHECKS_BEFORE = {
    "banded": [
        0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 22,
        24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 47, 49, 51, 53, 55, 57,
        59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 78, 80, 82, 84, 86, 88, 90, 92,
        94, 96, 98, 100, 102, 104, 106, 108, 109, 111, 113, 115, 117, 119, 121,
        123, 125, 127, 129, 131, 133, 135, 137, 139, 140, 142, 144, 146, 148,
        150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 171, 173, 175,
        177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 202,
        204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
        232, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257,
        259, 261, 263, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
        286, 288, 290, 292, 294, 295, 297, 299, 301, 303, 305, 307, 309, 311,
        313, 315, 317, 319, 321, 323, 325, 326, 328, 330, 332, 334, 335, 337,
        339, 341, 343, 344, 346, 348, 350, 352, 353, 355, 357, 359, 361, 362,
        364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390,
        392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418,
        420, 422, 424, 426, 428, 430, 432, 434, 436, 438, 440, 442, 444, 446,
        448, 450, 452, 454, 456, 458, 460, 462, 464, 466, 468, 470, 472, 474,
        476, 478, 480,
    ],
    "rowMajor": [
        0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 20, 22,
        24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 47, 49, 51, 53, 55, 57,
        59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 78, 80, 82, 84, 86, 88, 90, 92,
        94, 96, 98, 100, 102, 104, 106, 108, 109, 111, 113, 115, 117, 119, 121,
        123, 125, 127, 129, 131, 133, 135, 137, 139, 140, 142, 144, 146, 148,
        150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 171, 173, 175,
        177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 202,
        204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230,
        232, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257,
        259, 261, 263, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
        286, 288, 290, 292, 294, 295, 297, 299, 301, 303, 305, 307, 309, 311,
        313, 315, 317, 319, 321, 323, 325, 326, 328, 330, 332, 334, 336, 338,
        340, 342, 344, 346, 348, 350, 352, 354, 356, 357, 359, 361, 363, 365,
        367, 369, 371, 373, 375, 377, 379, 381, 383, 385, 387, 388, 390, 392,
        394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 419,
        421, 423, 425, 427, 429, 431, 433, 435, 437, 439, 441, 443, 445, 447,
        449, 450, 452, 454, 456, 458, 460, 462, 464, 466, 468, 470, 472, 474,
        476, 478, 480,
    ],
}

# The published schedules cap the total breaks a board can ever carry (see
# ScanSolver.SCHEDULE_BLACKWOOD / SCHEDULE_VERHAARD); a computed value outside
# this range means something about the row doesn't match our assumptions, and
# it is safer to leave it NULL than to write a guess.
MAX_PLAUSIBLE_BREAKS = 12


def recover_breaks(config, best_depth, matched_edges):
    """Return the breaks count for one row, or None if it can't be recovered."""
    engine = (config or {}).get("engine")
    if engine != "scan":
        # MrvSolver never slips; neither did the single-solver app this
        # project started as, before "engine" existed as a concept at all.
        # This needs no edge count, so it must come before the check below:
        # the oldest attempts have none, and are exactly the ones that were
        # never able to slip.
        return 0
    if matched_edges is None or best_depth is None or best_depth <= 0:
        return None
    fill_order = (config or {}).get("fillOrder", "banded")
    table = CHECKS_BEFORE.get(fill_order)
    if table is None or best_depth >= len(table):
        return None
    breaks = table[best_depth] - matched_edges
    if breaks < 0 or breaks > MAX_PLAUSIBLE_BREAKS:
        return None
    return breaks


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB
    if not os.path.isfile(path):
        print("no database at %s" % path)
        return 1

    conn = sqlite3.connect(path, timeout=30)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT id, best_depth, matched_edges, config_json FROM attempts "
        "WHERE breaks IS NULL").fetchall()

    updates = []
    unrecoverable = 0
    for r in rows:
        try:
            cfg = json.loads(r["config_json"]) if r["config_json"] else {}
        except (TypeError, ValueError):
            cfg = {}
        breaks = recover_breaks(cfg, r["best_depth"], r["matched_edges"])
        if breaks is None:
            unrecoverable += 1
            continue
        updates.append((breaks, r["id"]))

    conn.executemany("UPDATE attempts SET breaks=? WHERE id=?", updates)
    conn.commit()

    clean = sum(1 for b, _ in updates if b == 0)
    print("rows examined      : %d" % len(rows))
    print("breaks recovered   : %d (%d of them clean, 0 breaks)" % (len(updates), clean))
    print("left NULL          : %d (no matched-edge count, or outside the plausible range)"
          % unrecoverable)

    best_row = conn.execute(
        "SELECT id, best_depth FROM attempts WHERE status != 'running' "
        "AND nodes > 0 AND breaks = 0 ORDER BY best_depth DESC, id ASC LIMIT 1").fetchone()
    if best_row:
        print("clean pieces record after recovery: %d (attempt #%d)"
              % (best_row["best_depth"], best_row["id"]))
    conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
